### Checklist for submission

It is extremely important to make sure that:

1. Everything runs as expected (no bugs when running cells);
2. The output from each cell corresponds to its code (don't change any cell's contents without rerunning it afterwards);
3. All outputs are present (don't delete any of the outputs);
4. Fill in all the places that say `# YOUR CODE HERE`, or "**Your answer:** (fill in here)".
5. Never copy/paste any notebook cells. Inserting new cells is allowed, but it should not be necessary.
6. The notebook contains some hidden metadata which is important during our grading process. **Make sure not to corrupt any of this metadata!** The metadata may for example be corrupted if you copy/paste any notebook cells, or if you perform an unsuccessful git merge / git pull. It may also be pruned completely if using Google Colab, so watch out for this. Searching for "nbgrader" when opening the notebook in a text editor should take you to the important metadata entries.
7. Although we will try our very best to avoid this, it may happen that bugs are found after an assignment is released, and that we will push an updated version of the assignment to GitHub. If this happens, it is important that you update to the new version, while making sure the notebook metadata is properly updated as well. The safest way to make sure nothing gets messed up is to start from scratch on a clean updated version of the notebook, copy/pasting your code from the cells of the previous version into the cells of the new version.
8. If you need to have multiple parallel versions of this notebook, make sure not to move them to another directory.
9. Although not forced to work exclusively in the course `conda` environment, you need to make sure that the notebook will run in that environment, i.e. that you have not added any additional dependencies.

**FOR HA1, HA2, HA3 ONLY:** Failing to meet any of these requirements might lead to either a subtraction of POEs (at best) or a request for resubmission (at worst).

We advise you to perform the following steps before submission to ensure that requirements 1, 2, and 3 are always met: **Restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All). This might require a bit of time, so plan ahead for this (and possibly use a cloud GPU in HA1 and HA2 for this step). Finally press the "Save and Checkout" button before handing in, to make sure that all your changes are saved to this .ipynb file.

### Fill in name of notebook file
This might seem silly, but the version check below needs to know the filename of the current notebook, which is not trivial to find out programmatically.

You might want to have several parallel versions of the notebook, and it is fine to rename the notebook as long as it stays in the same directory. **However**, if you do rename it, you also need to update its own filename below:

In [ ]:
nb_fname = "XXX.ipynb"

### Fill in group number and member names (use NAME2 and GROUP only for HA1, HA2 and HA3):

In [ ]:
NAME1 = ""
NAME2 = ""
GROUP = ""

### Check Python version

In [ ]:
from platform import python_version_tuple

assert (
    python_version_tuple()[:2] == ("3", "11")
), "You are not running Python 3.11. Make sure to run Python through the course Conda environment."

### Check that notebook server has access to all required resources, and that notebook has not moved

In [ ]:
import os

nb_dirname = os.path.abspath("")
assignment_name = os.path.basename(nb_dirname)
assert assignment_name in [
    "IHA1",
    "IHA2",
    "HA1",
    "HA2",
    "HA3",
], "[ERROR] The notebook appears to have been moved from its original directory"

### Verify correct nb_fname

In [ ]:
from IPython.display import HTML, display

try:
    display(
        HTML(
            r'<script>if("{nb_fname}" != IPython.notebook.notebook_name) {{ alert("You have filled in nb_fname = \"{nb_fname}\", but this does not seem to match the notebook filename \"" + IPython.notebook.notebook_name + "\"."); }}</script>'.format(
                nb_fname=nb_fname
            )
        )
    )
except NameError:
    assert False, "Make sure to fill in the nb_fname variable above!"

### Verify that your notebook is up-to-date and not corrupted in any way

In [ ]:
import sys

sys.path.append("..")
from ha_utils import check_notebook_uptodate_and_not_corrupted

check_notebook_uptodate_and_not_corrupted(nb_dirname, nb_fname)

# IHA1 - Assignment

Welcome to the first individual home assignment!  

This assignment consists of two parts:
 * Python and NumPy exercises;
 * Build a deep neural network for forward propagation.
  
The focus of this assignment is for you to gain practical knowledge with implementing forward and backward propagation of deep neural networks **without** using any deep learning framework. You will also gain practical knowledge in two of Python's scientific libraries, [NumPy](https://numpy.org/doc/1.26/) and [Matplotlib](https://matplotlib.org/devdocs/index.html). Note that NumPy and [PyTorch](https://pytorch.org/) (the deep learning framework used in this course) share a lot of similarities with how they handle arrays/tensors, so in the coming assignments, you can leverage on what you learn here.

Skeleton code is provided for most tasks, and every part you are expected to implement is marked with **YOUR CODE HERE**. Throughout the assignment, you will also need to submit written answers to some questions. These questions are mainly to make you reflect on some particular topics, and your answers will not be graded in detail.

We expect you to search and learn by yourself any commands you think are useful for these tasks. Don't limit yourself to what was taught in CL1. Use the help function, [stackoverflow](https://stackoverflow.com/), Google, the [Python documentation](https://docs.python.org/3.11/library/index.html) and the [NumPy](https://numpy.org/doc/2.0/index.html) documentation to your advantage.

**IMPORTANT NOTE**: The tests available are not exhaustive, meaning that if you pass a test you have avoided the most common mistakes, but it is still not guaranteed that your solution is 100% correct. To pass this assignment, we expect you to pass all tests. 

While we use the tests for grading here, we encourage you to implement unit tests like these yourself when developing any code. Sanity-checking that your code behaves as expected can save you a lot of time down the road.

Let's start by importing the necessary libraries below.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import utils.tests.iha1_tests as iha1_tests
from sklearn.datasets import fetch_openml

## 1. Lists and arrays introduction
First, we will warm up with a Python exercise and few NumPy exercises.

### 1.1 List comprehensions
Examine the code snippet provided below.

In [ ]:
def square_even_numbers(max_num=24):
    my_list = []
    for i in range(max_num + 1):
        if i % 2 == 0:
            my_list.append(i**2)
    return my_list


print(square_even_numbers(24))

This is not a very "[pythonic](http://docs.python-guide.org/en/latest/writing/style/)" way of writing. Lets re-write the code above using a [list comprehension](https://docs.python.org/2/tutorial/datastructures.html#list-comprehensions). The result will be less code, more readable and elegant. Your solution should be able to fit into one line of code.

In [ ]:
def square_even_numbers(max_num=24):
    # YOUR CODE HERE
    return my_list


print(square_even_numbers())

In [ ]:
assert square_even_numbers(1) == [0]
assert square_even_numbers(24) == [
    0,
    4,
    16,
    36,
    64,
    100,
    144,
    196,
    256,
    324,
    400,
    484,
    576,
]
assert len(square_even_numbers(-1)) == 0
assert len(square_even_numbers(100)) == 51
assert sorted(square_even_numbers(123)) == square_even_numbers(123)

### 1.2 Arrays, vectors, matrices, and tensors
Many operations in deep learning revolve around handling and modifying data structures such as vectors (1D), matrices (2D), and tensors (N-D). In NumPy, all of these can be represented using arrays (in PyTorch, we'll use torch.Tensor's instead). Thus, it is important for you to understand these structures and the effects of applying different operations (matrix multiplications, reshaping, etc.).

Run the cell below to create a numpy array.   

In [ ]:
my_arr = np.array([1, 9, 25, 49])
print(my_arr)
print(my_arr.shape)
print(my_arr.ndim)

The above result indicates that **my_arr** is an array of 4 elements with shape (4,) and one dimension. You might be temped to think of this as a vector, but the behavior of this array and a vector in the linear algebra sense can be very different. It is important to separate the two types because it will save a lot of debugging time later on. Read more about numpy shapes [here](https://stackoverflow.com/a/22074424).

Run the code below to see how the transpose operation behaves differently between an array and vector.

In [ ]:
# print the shape of an array and the shape of a transposed array
print("my_arr is an array of shape:")
print(my_arr.shape)
print("The transpose of my_arr has the shape:")
print(my_arr.T.shape)

# print the shape of a column vector and the transpose of a column vector
my_col_vec = my_arr.reshape(4, 1)
print("my_col_vec is a vector of shape:")
print(my_col_vec.shape)
print("The transpose of my_col_vec has the shape:")
print(my_col_vec.T.shape)

As an effect, matrix multiplication between arrays of different shape can give very different results.

In [ ]:
print("The matrix multiplication between my_arr and my_arr has shape:")
print((my_arr @ my_arr).shape)

print("The matrix multiplication between my_arr and my_col_vec has shape:")
print((my_arr @ my_col_vec).shape)

print("The matrix multiplication between my_col_vec.T and my_col_vec has shape:")
print((my_col_vec.T @ my_col_vec).shape)

print("The matrix multiplication between my_col_vec and my_col_vec.T has shape:")
print((my_col_vec @ my_col_vec.T).shape)

print("The matrix multiplication between my_col_vec and my_col_vec raises an error:")
try:
    print(my_col_vec @ my_col_vec)
except ValueError as e:
    print(e)

print("The matrix multiplication between my_col_vec and my_arr raises an error:")
try:
    print(my_col_vec @ my_arr)
except ValueError as e:
    print(e)

This, then has implications for multiplications with a matrix. One dimensional arrays can be both left-, and right multiplied with matrices.

In [ ]:
my_matrix = np.random.rand(4, 4).round(2)  # We round for readability
print("my_matrix is a matrix with the following values and shape:")
print(my_matrix)
print(my_matrix.shape)

arr_times_matrix = my_arr @ my_matrix
matrix_times_arr = my_matrix @ my_arr
print("The matrix multiplication between my_matrix and my_arr has shape:")
print((arr_times_matrix).shape)

print("The matrix multiplication between my_arr and my_matrix has shape:")
print((matrix_times_arr).shape)

print("But their results are not the same:")
print(f"arr_times_matrix: {arr_times_matrix}")
print(f"matrix_times_arr: {matrix_times_arr}")

Wheras the reshaped version behaves like a column vector as expected.

In [ ]:
matrix_times_col_vec = my_matrix @ my_col_vec
print(
    f"The matrix multiplication between my_matrix {my_matrix.shape} and my_col_vec {my_col_vec.shape} has shape:"
)
print((matrix_times_col_vec).shape)
print(
    f"Matrix times column vector gives the same values as the matrix times the array:"
)
print((matrix_times_col_vec.flatten() == matrix_times_arr).all())

row_vec_times_matrix = my_col_vec.T @ my_matrix
print(
    f"The matrix multiplication between my_col_vec.T {my_col_vec.T.shape} and my_matrix {my_matrix.shape} has shape:"
)
print((row_vec_times_matrix).shape)
print(f"Row vector times matrix gives the same values as the array times the matrix:")
print((row_vec_times_matrix.flatten() == arr_times_matrix).all())

To check your understanding, implement the following function which caluclates the resulting shape when multiplying two arrays of shape `(a, b)` and `(c, d)`. If the operation is not possible, return `None`.

In [ ]:
def out_shape(shape1, shape2):
    """
    Calculate the shape of the resulting matrix when multiplying two arrays.

    Arguments:
    shape1 -- a tuple of 2 positive integers representing the shape of the first array
    shape2 -- a tuple of 2 positive integers representing the shape of the second array

    Returns:
    A tuple of integers representing the shape of the resulting matrix
    Returns None if the shapes are not compatible for matrix multiplication
    """
    # YOUR CODE HERE

In [ ]:
assert isinstance(out_shape((1, 4), (4, 1)), tuple)
assert out_shape((1, 4), (4, 1)) == (1, 1)
assert out_shape((1, 1), (1, 1)) == (1, 1)
assert out_shape((4, 1), (4, 1)) == None


As a side-note, there are multiple different types of multiplication in NumPy such as [matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) (@), [multiply](https://numpy.org/doc/stable/reference/generated/numpy.multiply.html) (*), and [dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html). Make sure to use the right one for each task.

### 1.3 Numpy exercises
Now run the cell below to create the numpy array `numbers` and then complete the exercises sequentially.

In [ ]:
numbers = np.arange(24)
print(numbers)

In [ ]:
# TODO: reshape numbers into a 6x4 matrix
# YOUR CODE HERE
print(numbers)

In [ ]:
# sample output from cell above for reference
#  [[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]
#   [12 13 14 15]
#   [16 17 18 19]
#   [20 21 22 23]]

In [ ]:
# test case
iha1_tests.test_numpy_reshape(numbers)

In [ ]:
# TODO: set the element of the last row of the last column to zero
# Hint: Try what happends when indices are negative
# YOUR CODE HERE
print(numbers)

In [ ]:
# sample output from cell above for reference
#  [[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]
#   [12 13 14 15]
#   [16 17 18 19]
#   [20 21 22  0]]

In [ ]:
# test case
iha1_tests.test_numpy_neg_ix(numbers)

In [ ]:
# TODO: set every element of the first row to 0
# YOUR CODE HERE
print(numbers)

In [ ]:
# sample output from cell above for reference
#  [[ 0  0  0  0]
#   [ 4  5  6  7]
#   [ 8  9 10 11]
#   [12 13 14 15]
#   [16 17 18 19]
#   [20 21 22  0]]

In [ ]:
# test case
iha1_tests.test_numpy_row_ix(numbers)

In [ ]:
# TODO: append a 1x4 row vector of zeros to `numbers`,
# resulting in a 7x4 matrix where the new row of zeros is the last row
# Hint: A new matrix must be created in the procedure. Numpy arrays are not dynamic.
# YOUR CODE HERE
print(numbers)
print(numbers.shape)

In [ ]:
# sample output from cell above for reference
#   [[ 0  0  0  0]
#    [ 4  5  6  7]
#    [ 8  9 10 11]
#    [12 13 14 15]
#    [16 17 18 19]
#    [20 21 22  0]
#    [ 0  0  0  0]]
#  (7, 4)

In [ ]:
# test case
iha1_tests.test_numpy_append_row(numbers)

In [ ]:
# TODO: set all elements with a value greater than 10 to the value 1
# YOUR CODE HERE
print(numbers)

In [ ]:
# sample output from cell above for reference
#  [[ 0  0  0  0]
#   [ 4  5  6  7]
#   [ 8  9 10  1]
#   [ 1  1  1  1]
#   [ 1  1  1  1]
#   [ 1  1  1  0]
#   [ 0  0  0  0]]

In [ ]:
# test case
iha1_tests.test_numpy_bool_matrix(numbers)

In [ ]:
# TODO: compute the sum of every row and replace `numbers` with the answer
# YOUR CODE HERE
print(numbers.shape)
print(numbers)

In [ ]:
# sample output from cell above for reference
#   (7,)
#   [ 0 22 28  4  4  3  0]

In [ ]:
# test case
iha1_tests.test_numpy_sum(numbers)

## 2 Building your first neural network
It is time to start implementing your first neural network. In this lab youw will focus on the fundamentals of forward and backpropagation. As the main goal is for you to proper learn the fundamentals and get a solid understanding, the neural networks in this lab are kept very simple. In upcoming labs you will build more advanced networks, but the principles learned in this lab still holds true for more complex problems and network architectures.

### 2.1 Your first simple function (forward propagation)

To start things off, we will begin with a simple scalar and linear function
\begin{equation}
    y = w * x + b
\end{equation}
where $x$ is some scalar input. As you might recall, this is very similar to the function represented by a single neuron in a network. Here we have left out the activation function for now, and only focus on the scalar case for simplicity.

Start by implementing this function in the cell below. We call it forward as it's comparable to doing forward propagation for a single neuron (without any activation function).

In [ ]:
def forward(x, w, b):
    """Implement the forward pass of a linear neuron.

    Arguments:
    x - a scalar input of type 'float'
    w - a scalar weight of type 'float'
    b - a scalar bias of type 'float'

    Returns:
    y - the output of the neuron, a scalar of type 'float'
    """
    y = None
    # YOUR CODE HERE
    return y

We can visualize the function for some chosen input interval, and some choice of the weight $w$ and the bias $b$.

In [ ]:
xs = np.linspace(-3, 3, 1000)
w = 5.0
b = 2.0
plt.plot(xs, forward(xs, w, b), label=f"y = {w}x + {b}")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.show()

Let's also add a data point $(x, y) = (1.5, 14.0)$ and visualize that in the same plot as our line.

In [ ]:
data = np.array([1.5, 14.0])  # x, y
plt.plot(xs, forward(xs, w, b), label=f"y = {w}x + {b}")
plt.plot(data[0], data[1], "ro", label=f"({data[0]}, {data[1]})")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.show()

As you can see in the plot, our line doesn't quite go through the data point.

Manually find some parameters for $w$ and $b$ such that your line fits the data point. 

In [ ]:
# YOUR CODE HERE
plt.plot(xs, forward(xs, w, b), label=f"y = {w}x + {b}")
plt.plot(data[0], data[1], "ro", label=f"({data[0]}, {data[1]})")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.show()

In [ ]:
assert forward(data[0], w, b) == data[1]

### 2.2 Using the derivative of the error

We can also do something a bit more general and use the derivative of the error between our line and the point to find better parameters for our function.
First, we will need to define some function that describes the error between our line and the point.
Implement an error function that returns the squared error between some prediction from our function, $y_{pred}$, and some true value $y_{true}$.

In [ ]:
def error_function(y_pred, y_true):
    """Implement the error function as the squared error between the true and predicted value.

    Arguments:
    y_pred - a scalar value, the predicted value
    y_true - a scalar value, the true value

    Returns:
    error - a scalar value, the squared error between the true and predicted value
    """
    error = None
    # YOUR CODE HERE
    return error

In [ ]:
assert (
    np.abs(error_function(np.array(13.37), np.array(0.0)) - 178.75689999999997) < 0.01
)

Next, we need to know how the error changes when our function changes. In other words, we need to know the derivative of the error function with respect to our function, $\frac{\partial e}{\partial y}$.

Implement $\frac{\partial e}{\partial y}$ in the cell below.

In [ ]:
def de_dy(y_pred, y_true):
    """Implement the derivative of the error function with respect to the predicted value.

    Arguments:
    y_pred - a scalar value, the predicted value
    y_true - a scalar value, the true value

    Returns:
    derivative - a scalar value, the derivative of the error with respect to the predicted value
    """
    derivative = None
    # YOUR CODE HERE
    return derivative

In [ ]:
# Test the derivative function for our original parameters w = 5.0, b = 2.0
w, b = 5.0, 2.0
x, y_true = data
y_pred = forward(x, w, b)
print("The error for the original parameters: ", error_function(y_pred, y_true))
print("The derivative of the error with respect to y: ", de_dy(y_pred, y_true))

In [ ]:
assert error_function(y_pred, y_true) == 20.25
assert de_dy(y_pred, y_true) == -9.0

What can you tell from this derivative? How can it guide you in moving your line? In particular, what does the sign of the derivative tell you? 

**Your answer:** (fill in here)

What we are really interested in is how the error changes with respect to the parameters w and b. In the end, those are the parameters that we can change to reduce the error.

We already know how the error changes with the output of our function from the exercise above. If we also manage to find out how our output changes with respect to our parameters $w$ and $b$, then we should in some magical way be able to finally compute how the error changes with respect to our parameters.

In the cell below, implement the derivative of our function with respect to the parameters $w$ and $b$.

In [ ]:
def dy_dw(x):
    """Implement the derivative of the function with respect to the parameter w.

    Arguments:
    x - a scalar value, the input to the function

    Returns:
    derivative - a scalar value, the derivative of the function with respect to w
    """
    derivative = None
    # YOUR CODE HERE
    return derivative


def dy_db():
    """Implement the derivative of the function with respect to the parameter b.

    Arguments:
    x - a scalar value, the input to the function

    Returns:
    derivative - a scalar value, the derivative of the function with respect to b
    """
    derivative = None
    # YOUR CODE HERE
    return derivative

Why doesn't the derivative of the function with respect to $b$ include $x$ as an input? 

**Your answer:** (fill in here)

Now that we know how the error changes with respect to the function, and how the function changes with respect to it's parameters, we should be able to somehow combine these results to compute how the error changes with respect to the parameters of our function.

Implement the derivative of the error function with respect to the parameters $w$ and $b$ by using the results from the exercises above.

HINT: The [chain rule](https://en.wikipedia.org/wiki/Chain_rule) from your old calculus class is your friend here.

In [ ]:
def de_dw(x, y_pred, y_true):
    """Implement the derivative of the error function with respect to the parameter w.

    Arguments:
    x - a scalar value, the input to the function
    y_pred - a scalar value, the predicted value
    y_true - a scalar value, the true value

    Returns:
    derivative - a scalar value, the derivative of the function with respect to b
    """
    derivative = None
    # YOUR CODE HERE
    return derivative


def de_db(y_pred, y_true):
    """Implement the derivative of the error function with respect to the parameter b.

    Arguments:
    y_pred - a scalar value, the predicted value
    y_true - a scalar value, the true value

    Returns:
    derivative - a scalar value, the derivative of the function with respect to b
    """
    derivative = None
    # YOUR CODE HERE
    return derivative

In [ ]:
print("The error for the original parameters: ", error_function(y_pred, y_true))
print("The derivative of the error with respect to w: ", de_dw(x, y_pred, y_true))
print("The derivative of the error with respect to b: ", de_db(y_pred, y_true))

In [ ]:
assert de_dw(x, y_pred, y_true) == -13.5
assert de_db(y_pred, y_true) == -9.0

What does these derivatives tell you? How would you use them to update the parameters $w$ and $b$ such that the error is reduced?

**Your answer:** (fill in here)

We will now implement a function for updating the parameters based on the derivatives you calculated in the previous cell. Move the parameters in the direction, such that the error is decreased. The function includes a step size as an input, which scales the size of the update step. You can keep this as the default value.

In [ ]:
def update_params(w, b, de_dw, de_db, step_size=0.1):
    """Implement the update step of parameters w and b, based on the derivatives of the error function with respect to these parameters.

    Arguments:
    w - a scalar value, the weight parameter
    b - a scalar value, the bias parameter
    de_dw - a scalar value, the derivative of the error with respect to w
    de_db - a scalar value, the derivative of the error with respect to b
    step_size - a scalar value, the step size for the update step

    Returns:
    w - a scalar value, the updated weight parameter
    b - a scalar value, the updated bias parameter
    """
    # YOUR CODE HERE
    return w, b

If implemented correctly, we should see a decrease in the error after one update step.

In [ ]:
print("The original parameters: ", w, b)
print("The error for the original parameters: ", error_function(y_pred, y_true))

w_updated, b_updated = update_params(
    w, b, de_dw(x, y_pred, y_true), de_db(y_pred, y_true)
)
print("The updated parameters: ", w_updated, b_updated)
y_pred_updated = forward(x, w_updated, b_updated)
print("The error for the updated parameters: ", error_function(y_pred_updated, y_true))

In [ ]:
assert error_function(y_pred_updated, y_true) < error_function(y_pred, y_true)

Why do we use a step size when updating the parameters instead of using the gradients directly?

**Your answer:** (fill in here)

As you might have noticed, a single update step was not enough to find a good fit. Instead, let us iteratively update our parameters, where each iteration uses the updated parameters from the last iteration to compute a new error and derivatives.

Implement a function that iteratively updates your parameters, using the functions you have implemented earlier in the lab. Use the default values for `iterations` and `step_size`.

In [ ]:
def optimize_parameters(x, y_true, w, b, iterations=10, step_size=0.1):
    """Implement a function that iteratively updates the parameters w and b.

    Arguments:
    x - a scalar value, the input to the function
    y_true - a scalar value, the true value
    w - a scalar value, the weight parameter
    b - a scalar value, the bias parameter
    iterations - a scalar value, the number of iterations for the optimization
    step_size - a scalar value, the step size for the update step

    Returns:
    w - a scalar value, the updated weight parameter
    b - a scalar value, the updated bias parameter
    """
    for i in range(iterations):
        # YOUR CODE HERE
        print(f"Iteration {i} | Error: ", error_function(y_pred, y_true))
    return w, b

Test your iterative optimizer on the initial parameters from before.

In [ ]:
w_optimized, b_optimized = optimize_parameters(data[0], data[1], 5.0, 2.0)
plt.plot(
    xs,
    forward(xs, w_optimized, b_optimized),
    label=f"y = {round(w_optimized, 3)}x + {round(b_optimized, 3)}",
)
plt.plot(data[0], data[1], "ro", label=f"({data[0]}, {data[1]})")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.show()

Hopefully, you should see a rapid decrease of the error in the first few iterations, and the resulting error should be close to zero after 10 iterations.

How would a different step size affect the optimization? Why?

**Your answer:** (fill in here)

The process we have just implemented is called gradient descent. It is a simple optimization algorithm that is used to minimize a function by iteratively moving in the direction of steepest descent.
In our case, the function we are trying to minimize is the error between our line and the point, and the parameters we are optimizing are w and b.
The way we propagate the derivative of the error throughout the function to update the parameters is called backpropagation. It is a key concept in neural networks and deep learning, but is as simple as the chain rule in calculus at its core.
In deep learning, we usually refer to the error function as the loss function, and the derivatives that we have propagated from our loss function to our parameters are referred to as gradients.

### 2.3 Activation functions
The function we have used so far is not very exciting, and only lets us describe the rather boring family of linear functions. As you have already seen in the video and lecture material, we add an activation function to our otherwise linear neuron to be able to also model non-linear functions.

In the coming part of the lab we will use the notation that you might find familiar from the lectures, where $z = w*x + b$ denotes the output before activation, and $a = g(z)$ denotes the output after activation.

Lets start with implementing some common activation functions. To make them slightly more useful, we ask you to implement them such that they can handle vectorized input.

Due to the change of notation, we can make the following alias to simplify things:

In [ ]:
de_dz = de_dy
dz_dw = dy_dw
dz_db = dy_db

#### 2.3.1 ReLU
The neural network will use the ReLU activation function in every layer except for the last. ReLU does element-wise comparison of the input matrix. For example, if the input is `X`, and `X[i,j] == 2` and `X[k,l] == -1`, then after applying ReLU, `X[i,j] == 2` and `X[k,l] == 0` should be true.  

The formula for implementing ReLU for a single neuron $i$ is:
\begin{equation}
relu(z_i) = 
    \begin{cases}
      0, & \text{if}\ z_i \leq 0 \\
      z_i, & \text{otherwise}
    \end{cases}
\end{equation}

Now implement `relu` in vectorized form

In [ ]:
def relu(z):
    """Implement the ReLU activation function

    Arguments:
    z - the input of the activation function. Has a type of 'numpy.ndarray'

    Returns:
    a - the output of the activation function. Has a type of numpy.ndarray and the same shape as 'z'
    """

    a = None  # TODO
    # YOUR CODE HERE

    return a

In [ ]:
# test case
iha1_tests.test_relu_forward(relu)

Can you name some of the advantages of the ReLU activation function? (We will not grade this answer in detail.)

**Your answer:** (fill in here)

#### 2.3.2 Sigmoid
The sigmoid activation function is common for binary classification. This is because it squashes its input to the range [0,1].  
Implement the activation function `sigmoid` using the formula:  
\begin{equation}
    \sigma(z) = \frac{1}{1 + e^{-z}}
\end{equation}

In [ ]:
def sigmoid(z):
    """Implement the sigmoid activation function

    Arguments:
    z - the input of the activation function. Has a type of 'numpy.ndarray'

    Returns:
    a - the output of the activation function. Has a type of 'numpy.ndarray' and the same shape as 'z'
    """

    a = None  # TODO
    # YOUR CODE HERE

    return a

In [ ]:
# test case
iha1_tests.test_sigmoid(sigmoid)

Why is the sigmoid activation function useful for binary classification? Feel free to use some numerical examples to show how the magnitudes of the variable $z$ affect the output of the sigmoid layer. (We will not grade this answer in detail.)

**Your answer:** (fill in here)

#### 2.3.3 Visualization
Make a plot using matplotlib to visualize the activation functions between the input interval [-3,3]. The plot should have the following properties
 * one plot should contain a visualization of both `ReLU` and `sigmoid`;
 * x-axis: range of values between [-3,3], **hint**: np.linspace;
 * y-axis: the value of the activation functions at a given input `x`;
 * a legend explaining which line represents which activation function.

In [ ]:
# TODO: make a plot of ReLU and sigmoid values in the interval [-3,3]

# YOUR CODE HERE

#### 2.3.4 Softmax
Another common activation function is the softmax activation function. It is often used for the final layer of the neural network in classification tasks. Implement `softmax` according to the formula below. The subtraction of the maximum value is there solely to avoid overflows in a practical implementation.
\begin{equation}
softmax(z_i) = \frac{e^{z_i - max(\mathbf{z})}}{ \sum^j e^{z_j - max(\mathbf{z})}}
\end{equation}


In [ ]:
def softmax(z):
    """Implement the softmax activation function

    Arguments:
    z - the input of the activation function, shape (BATCH_SIZE, FEATURES) and type 'numpy.ndarray'

    Returns:
    a - the output of the activation function, shape (BATCH_SIZE, FEATURES) and type 'numpy.ndarray'
    """

    a = None  # TODO
    # YOUR CODE HERE

    return a

In [ ]:
# test case
iha1_tests.test_softmax(softmax)

What are the main differences between using `sigmoid` and `softmax` for multi-class classification problems? And when the number of classes is 2? (We will not grade this answer in detail.)

**Your answer:** (fill in here)

### 2.4 Putting the pieces together

Now you have implemented, and hopefully understood, the building blocks needed to build your first neural network. All that is left now is putting these pieces together.

#### 2.4.1 Implementing a layer

You will start with implementing a `Layer`-class. This will be convenient when later constructing your neural network. To keep things simple, and make use of the functions you've implemented earlier in this lab, we will stick to scalar input and having one neuron per layer. However, you will also add `ReLU` as an activation function this time.

Since you now need to also propagate your derivatives through the activation function, start with implementing the derivative of `ReLU`.

In [ ]:
def relu_derivative(x):
    """Implement the derivative of the ReLU activation function

    Arguments:
    x - the input of the activation function, shape (BATCH_SIZE, FEATURES) and type 'numpy.ndarray'

    Returns:
    dx - the derivative of the activation function, shape (BATCH_SIZE, FEATURES) and type 'numpy.ndarray'
    """
    dx = None
    # YOUR CODE HERE
    return dx

In [ ]:
assert relu_derivative(np.array(-1)) == 0
assert relu_derivative(np.array(1)) == 1

Now it's time to fill in the missing pieces of the `Layer`-class. The parameters of the layer should be initialized with random values. Think about how to initialize your parameters in a way that make sense with the chosen activation function (ReLU in this case). Hint: Look at the local gradient of ReLU and think about what ranges of values this gradient will be active and how it will affect the backpropagation.

In [ ]:
class Layer:
    """Implement a class for a neural network layer.

    The class should implement the forward and backward passes of the layer.
    """

    def __init__(self):
        """Implement the initialization of the layer parameters.

        Arguments:
        None

        Returns:
        None
        """

        # Parameters of the layer. Should be initialized randomly.
        self.w = None
        self.b = None
        # YOUR CODE HERE

        # Activation function for the layer.
        self.activation = relu
        self.activation_derivative = relu_derivative

        # Attributes to store the input and output of a layer during forward pass, for use in the backward passes.
        self.last_x = None
        self.last_a = None

    def forward(self, x):
        """Implement the forward pass of the layer.

        Arguments:
        x - the input to the layer, scalar of type 'float'

        Returns:
        a - the output of the layer, scalar of type 'float'
        """
        a = None
        # YOUR CODE HERE
        self.last_x = x
        self.last_a = a
        return a

    def backward(self, de_da, step_size=0.01):
        """Implement the backward pass of the layer. The backward pass should update the parameters of
        the layer and return the derivative of the error with respect to the input of the layer.

        Arguments:
        de_da - the derivative of the error with respect to the output of the layer, scalar of type 'float'
        step_size - the step size for the update step, scalar of type 'float'

        Returns:
        de_dx - the derivative of the error with respect to the input of the layer, scalar of type 'float'
        """
        # YOUR CODE HERE
        return de_dx

In [ ]:
test_layer = Layer()

# make sure w and b are initialized
assert test_layer.w is not None
assert test_layer.b is not None

# set to some values for tests
test_layer.w = np.array(10.0)
test_layer.b = np.array(-1.0)

# assert correct forward for some input
assert test_layer.forward(np.array(42.0)) == 419.0
assert test_layer.last_x == 42.0
assert test_layer.last_a == 419.0

# assert correct backward
assert test_layer.backward(np.array(42.0), step_size=0.01) == 420
assert np.abs(test_layer.w - (-7.64)) < 0.01
assert np.abs(test_layer.b - (-1.42)) < 0.01

#### 2.4.2 Building your network
Almost there! Now we just need to chain a bunch of layers together and we have ourselves a neural network.

In [ ]:
class NeuralNetwork:
    """Implement a class for a neural network.

    The class should implement the forward and backward passes of the neural network.
    """

    def __init__(self):
        self.layers = []

    def add_layer(self, layer):
        self.layers.append(layer)

    def forward(self, x):
        """Implement the forward pass of the neural network. The neural network should pass the input through all layers.

        Arguments:
        x - the input to the neural network, scalar of type 'float'

        Returns:
        x - the output of the neural network, scalar of type 'float'
        """
        # YOUR CODE HERE
        return x

    def backward(self, error_derivative, step_size=0.01):
        """Implement the backward pass of the neural network. The neural network should pass the error derivative through
        all layers and update the parameters of each layer.

        Arguments:
        error_derivative - the derivative of the error with respect to the output of the neural network, scalar of type 'float'
        """
        # YOUR CODE HERE

Lets test the forward pass of your network.

In [ ]:
neural_network = NeuralNetwork()
layer1 = Layer()
layer2 = Layer()
neural_network.add_layer(layer1)
neural_network.add_layer(layer2)

y_pred = neural_network.forward(x)
print("The error for the original parameters: ", error_function(y_pred, y_true))
plt.plot(xs, neural_network.forward(xs), label=f"neural network")
plt.plot(data[0], data[1], "ro", label=f"({data[0]}, {data[1]})")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.show()

#### 2.4.3 Training your network
Now let's also implement the iterative optimization that we did before. Here `y_pred` refers to the output from the last layer of your network, commonly referred to as the prediction.

In deep learning, we usually refer to the optimization process as "training" the network. Thus, the function to iteratively update the parameters of your network is here called `train`, but the principle remains the same as before. 

In [ ]:
def train(x, y_true, neural_network, iterations=10, step_size=0.01):
    """Implement the training loop for the neural network. The training loop should update the parameters of the neural network
    based on the error between the predicted and true values.

    Arguments:
    x - the input to the neural network, scalar of type 'float'
    y_true - the true value of the output, scalar of type 'float'
    neural_network - the neural network object
    iterations - the number of training iterations, scalar of type 'int'
    step_size - the step size for the update step, scalar of type 'float'
    """

    for i in range(iterations):
        # YOUR CODE HERE
        print(f"Iteration {i} | Error: ", error_function(y_pred, y_true))

Finally, we can test the training loop on the same simple example as we did before.

In [ ]:
train(data[0], data[1], neural_network)

plt.plot(xs, neural_network.forward(xs), label=f"neural network")
plt.plot(data[0], data[1], "ro", label=f"({data[0]}, {data[1]})")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.show()

Hopefully, you should again see the error decrease at each iteration of our training loop. In the end, the error should be close to zero. 

## 3 Building a deep neural network

Very few problems are one-dimensional and cannot be solved with the simple scalar network we have implemented so far. 
Thus, as the final part of this assignment, you will now implement the `Layer` and `NeuralNetwork` classes such that they support multi-dimensional input, and any choice of activation function.
However, you will be given code for the backward propagation and only need to implement the forward propagation.

(If you want to try to derive the backward propagation yourself [this document](https://compsci697l.github.io/docs/vecDerivs.pdf) could be helpful to simplify the derivatives for higher dimensions)

Recall the formula for forward propagation of an arbitrary layer $l$:

\begin{equation}
\mathbf{a}^{[l]} = g(\mathbf{z}^{[l]}) = g(\mathbf{a}^{[l-1]}\mathbf{w}^{[l]} +\mathbf{b}^{[l]})
\end{equation}

where $g$ is the activation function given by `activation_fn`, which can be relu, sigmoid or softmax.


### 3.1 Initialize weights
You will first implement a helper function that takes the shape of a layer as input, and returns an initialized weight matrix $\mathbf{W}$ and bias vector $\mathbf{b}$ as output. The matrix $\mathbf{W}$ should be sampled from a normal distribution with mean 0 and standard deviation 2, and $\mathbf{b}$ should be initialized to all zeros.

In [ ]:
def initialize_weights(layer_shape):
    """Implement initialization of the weight matrix and biases

    Arguments:
    layer_shape - a tuple of length 2, type (int, int), that determines the dimensions of the weight matrix: (input_dim, output_dim)

    Returns:
    w - a weight matrix with dimensions of 'layer_shape', (input_dim, output_dim), that is normally distributed with
        properties mu = 0, stddev = 2. Has a type of 'numpy.ndarray'
    b - a vector of initialized biases with shape (1,output_dim), all of value zero. Has a type of 'numpy.ndarray'
    """
    w = None  # TODO
    b = None  # TODO
    # YOUR CODE HERE

    return w, b

In [ ]:
# test case
iha1_tests.test_initialize_weights(initialize_weights)

### 3.2 Implementing the layer

In [ ]:
class Layer:
    """
    TODO: Build a class called Layer that satisfies the descriptions of the methods
    Make sure to utilize the helper functions you implemented before
    """

    def __init__(self, input_dim, output_dim, activation_fn=relu):
        """
        Arguments:
        input_dim - the number of inputs of the layer. type int
        output_dim - the number of outputs of the layer. type int
        activation_fn - a reference to the activation function to use. Should be 'relu' as a default
                        possible values are the 'relu', 'sigmoid' and 'softmax' functions you implemented earlier.
                        Has the type 'function'

        Attributes:
        w - the weight matrix of the layer, should be initialized with 'initialize_weights'
            and has the shape (INPUT_FEATURES, OUTPUT_FEATURES) and type 'numpy.ndarray'
        b - the bias vector of the layer, should be initialized with 'initialize_weights'
            and has the shape (1, OUTPUT_FEATURES) and type 'numpy.ndarray'
        activation_fn - a reference to the activation function to use.
                        Has the type 'function'
        """
        self.w, self.b = None, None  # TODO
        self.activation_fn = None  # TODO
        # YOUR CODE HERE

        self.input = None
        self.output = None

    def forward_prop(self, a_prev):
        """Implement the forward propagation module of the neural network layer
        Should use whatever activation function that 'activation_fn' references to

        Arguments:
        a_prev - the input to the layer, which may be the data 'X', or the output from the previous layer.
            a_prev has the shape of (BATCH_SIZE, INPUT_FEATURES) and the type 'numpy.ndarray'

        Returns:
        a - the output of the layer when performing forward propagation. Has the type 'numpy.ndarray'
        """

        a = None  # TODO
        # YOUR CODE HERE
        self.input = a_prev
        self.output = a

        return a

    def backward_prop(self, output_gradient, learning_rate):
        if self.activation_fn == relu:
            output_gradient *= relu_derivative(self.output)
        weights_gradient = np.dot(self.input.T, output_gradient)
        input_gradient = np.dot(output_gradient, self.w.T)
        self.w -= learning_rate * weights_gradient
        self.b -= learning_rate * np.sum(output_gradient, axis=0, keepdims=True)
        return input_gradient

In [ ]:
# test case, be sure that you pass the previous activation function tests before running this test
iha1_tests.test_layer(Layer, relu, sigmoid, softmax)

### 3.3 Implementing the neural network
You will now define the actual neural network class. It is an L-layer neural network, meaning that the number of layers and neurons in each layer is specified as input by the user. Once again, you will only focus on implementing the forward propagation part.

Read the descriptions in the comments and complete the **TODO**s.

In [ ]:
class NeuralNetwork:
    """
    TODO: Implement an L-layer neural network class by utilizing the Layer module defined above
    Each layer should use 'relu' activation function, except for the output layer, which should use 'softmax'
    """

    def __init__(self, input_n, layer_dims):
        """
        Arguments:
        input_n    - the number of inputs to the network. Should be the same as the length of a data sample
                     Has type int
        layer_dims - a python list or tuple of the number of neurons in each layer. Layer 'l' should have a weight matrix
                     with the shape ('layer_dims[l-1]', 'layer_dims[l]').
                     'layer_dims[-1]' is the dimension of the output layer.
                     Layer 1 should have the dimensions ('input_n', 'layer_dims[0]').
                     len(layer_dims) is the depth of the neural network
        Attributes:
        input_n - the number of inputs to the network. Has type int
        layers  - a python list of each layer in the network. Each layer should use the 'relu' activation function,
                  except for the last layer, which should use 'softmax'.
                  Has type 'list' containing layers of type 'Layer'
        """

        self.input_n = None  # TODO
        self.layers = None  # TODO
        # YOUR CODE HERE

    def forward_prop(self, x):
        """
        Implement the forward propagation procedure through the entire network, from input to output.
        You will now connect each layer's forward propagation function into a chain of layer-wise forward propagations.

        Arguments:
        x - the input data, which has the shape (BATCH_SIZE, NUM_FEATURES) and type 'numpy.ndarray'

        Returns:
        a - the output of the last layer after forward propagating through the every layer in 'layers'.
            Should have the dimension (BATCH_SIZE, layers[-1].w.shape[1]) and type 'numpy.ndarray'
        """
        a = None  # TODO
        # YOUR CODE HERE

        return a

    def backward_prop(self, output_gradient, learning_rate):
        for layer in reversed(self.layers):
            output_gradient = layer.backward_prop(output_gradient, learning_rate)

In [ ]:
# test case
iha1_tests.test_neuralnetwork(NeuralNetwork)

### 3.4 Training

All that is left now is the training loop for your network. You are already given a loss function and its derivative (loss is just another word for error) that will be suitable for the upcoming problem that you will train your network on. Implement the missing steps in the training loop.

In [ ]:
def compute_loss(output, y_true, epsilon=1e-10):
    p = np.clip(output, epsilon, 1 - epsilon)
    log_likelihood = -np.sum(y_true * np.log(p)) / y_true.shape[0]
    return log_likelihood


def compute_loss_gradient(output, y_true):
    return (output - y_true) / y_true.shape[0]


def train(neural_network, x_train, y_train, iterations, learning_rate):
    """Implement the training loop for the neural network. The training loop should update the parameters of the neural network
    based on the error between the predicted and true values.

    Arguments:
    neural_network - the neural network object
    x_train - the input to the neural network, shape (BATCH_SIZE, INPUT_FEATURES) and type 'numpy.ndarray'
    y_train - the true value of the output, shape (BATCH_SIZE, OUTPUT_FEATURES) and type 'numpy.ndarray'
    iterations - the number of training iterations, scalar of type 'int'
    learning_rate - the step size for the update step, scalar of type 'float'

    Returns:
    None
    """
    for iteration in range(iterations):
        # YOUR CODE HERE
        print(f"Iteration {iteration + 1}/{iterations} | Loss: {loss}")

You will now apply your newly created `NeuralNetwork`-class on a slightly more difficult problem than before. Given images of hand-drawn numbers, your network will be tasked with predicting the correct digit. For this we will use the famous [MNIST dataset](https://en.wikipedia.org/wiki/MNIST_database). Below, we have prepared the necessary code needed to load and visualize the data. Run the cells below to see the size of the dataset splits and a visualization of some samples from the dataset. 

In [ ]:
# Load MNIST data from sklearn
mnist = fetch_openml("mnist_784", version=1)
x, y = mnist["data"].to_numpy(), mnist["target"].to_numpy()

# Normalize the data
x = x / 255.0
y = y.astype(int)

# One-hot encode the labels
y_one_hot = np.zeros((y.size, y.max() + 1))
y_one_hot[np.arange(y.size), y] = 1

# Split into training and test sets
x_train, x_test = x[:60000], x[60000:]
y_train, y_test = y_one_hot[:60000], y_one_hot[60000:]

print(f"x_train shape: {x_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"x_test shape: {x_test.shape}")
print(f"y_test shape: {y_test.shape}")

In [ ]:
# Display the mnist data and labels for 3 samples
fig, axs = plt.subplots(1, 3)
for i in range(3):
    axs[i].imshow(x_train[i].reshape(28, 28), cmap="gray")
    axs[i].set_title(f"Label: {np.argmax(y_train[i])}")
    axs[i].axis("off")
plt.show()

Before training the network, we want some way of running predictions on test data and calculate some metric that tells us how our network performed. In this case, we want to calculate the accuracy of our network, meaning the ratio of correctly predicted samples out of the full test set. Implement the function `predict_and_correct`which takes in a `NeuralNetwork`-object and some test data, makes predictions using the neural network, and finally outputs the accuracy of the predictions.

In [ ]:
def predict_and_correct(model, x_test, y_test):
    """Implement a function that predicts the labels of the test data and calculates the accuracy of the predictions.

    Arguments:
    model - the neural network to use for prediction. Has type `NeuralNetwork`

    Returns:
    accuracy - the accuracy of the predictions. Has type 'float'
    """

    # YOUR CODE HERE

    return accuracy

Now you can first test the accuracy of your untrained network. 

In [ ]:
nn = NeuralNetwork(784, [64, 10])
print("Accuracy without training: ", predict_and_correct(nn, x_test, y_test))

How did it perform? Was it in line with your expectations? Why/why not?

**Your answer:** (fill in here)

Let's train the network for some iterations and again evaluate the performance.

In [ ]:
# Train the neural network
train(nn, x_train, y_train, iterations=50, learning_rate=0.1)

In [ ]:
print("Accuracy after training: ", predict_and_correct(nn, x_test, y_test))

How did the network perform after training? Was it in line with your expectations? Why/why not?

**Your answer:** (fill in here)

Below is some code to visualize your networks prediction for a chosen sample in the test set.

In [ ]:
# Create a function that visualizes the data, prediction and true label for some sample index in the test set
def visualize_prediction(model, x_test, y_test, sample_idx):
    """Implement a function that visualizes the data, prediction and true label for a sample in the test set.

    Arguments:
    model - the neural network to use for prediction. Has type `NeuralNetwork`
    x_test - the input to the neural network, shape (BATCH_SIZE, INPUT_FEATURES) and type 'numpy.ndarray'
    y_test - the true value of the output, shape (BATCH_SIZE, OUTPUT_FEATURES) and type 'numpy.ndarray'
    sample_idx - the index of the sample to visualize. Has type 'int'

    Returns:
    None
    """
    assert (sample_idx >= 0) & (
        sample_idx < x_test.shape[0]
    ), "Sample index out of bounds"

    y_pred = model.forward_prop(x_test[sample_idx : sample_idx + 1])
    plt.imshow(x_test[sample_idx].reshape(28, 28), cmap="gray")
    plt.title(
        f"Prediction: {np.argmax(y_pred)} | True label: {np.argmax(y_test[sample_idx])}"
    )
    plt.axis("off")
    plt.show()

In [ ]:
visualize_prediction(nn, x_test, y_test, 42)

## Congratulations!
You have successfully implemented a neural network from scratch using only NumPy!  